# Created using wingetcreate 1.5.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Initex.YogaDNS
PackageVersion: "1.41"
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- xml
Installers:
- Architecture: x86
  InstallerUrl: https://yogadns.com/download/YogaDNSSetup.exe
  InstallerSha256: 3EFCA5FCE94D7C732CADC3189BA4244D5AF615A0B97BFAF5913EDA21DD7B30D9
ManifestType: installer
ManifestVersion: 1.5.0
